---
title: "week 4"
author: "Simranjit"
date: "2022-10-04"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
library(ISLR)
library(MASS)
library(tidyverse)


```
```{r}
lm_ses <- lm(formula = medv ~ lstat, data = Boston)

```
```{r}
coef(lm_ses)

```
```{r}
summary(lm_ses)
```
```{r}
y_pred <- predict(lm_ses)
```

```{r}
 tibble(pred = y_pred, obs  = Boston$medv) %>%  ggplot(aes(x = pred, y = obs)) + geom_point() + theme_minimal() + geom_abline(slope = 1)
```
```{r}
pred_dat <- tibble(lstat = seq(0, 40, length.out = 1000))



```
```{r}
y_pred_new <- predict(lm_ses, newdata = pred_dat)
```
```{r}
p_scatter <- 
  Boston %>% 
  ggplot(aes(x = lstat, y = medv)) +
  geom_point() +
  theme_minimal() + geom_smooth(method ="lm") 

p_scatter
```
```{r}
pred_dat <- pred_dat %>% mutate(medv =  y_pred_new)
```
```{r}
p_scatter + geom_line(data = pred_dat)

```
```{r}
y_pred_95 <-  predict(lm_ses, newdata = pred_dat, interval = "confidence")
```
```{r}
head(y_pred_95)
```
```{r}
gg_pred <- tibble(
  medv = y_pred_95[,1],
  lstat = pred_dat$lstat,
  lower = y_pred_95[,3],
  upper = y_pred_95[,2]
)
gg_pred
```
```{r}
library("RColorBrewer")
brewer.pal(n = 11, name = "RdBu")
```
```{r}
Boston %>% 
  ggplot(aes(x = lstat, y = medv)) + 
  geom_ribbon(aes(ymin = lower, ymax = upper), data = gg_pred, fill = "#2166AC") +
  geom_point(colour ="#053061" ) + 
  geom_line(data = pred_dat, colour = "#00008b", size = 1) +
  theme_minimal() + 
  labs(x    = "Proportion of low SES households",
       y    = "Median house value",
       title = "Boston house prices")
  
```
# atleast 90% of the ribbons contain the fit line
```{r}
head(lm_ses)
tail(lm_ses)





```
```{r}
y_pred_95 <- predict(lm_ses, newdata = pred_dat, interval = "prediction")
gg_pred <- tibble(
  lstat = pred_dat$lstat,
  medv  = y_pred_95[, 1],
  lower = y_pred_95[, 2],
  upper   = y_pred_95[, 3]
)


Boston %>% 
  ggplot(aes(x = lstat, y = medv)) + 
  geom_ribbon(aes(ymin = lower, ymax = upper), data = gg_pred, fill = "#00008b44") +
  geom_point(colour = "#883321") + 
  geom_line(data = pred_dat, colour = "#00008b", size = 1) +
  theme_minimal() + 
  labs(x     = "Proportion of low SES households",
       y     = "Median house value",
       title = "Boston house prices")


```
```{r}
mse <- function(y_true, y_pred) { mean((y_true - y_pred))^2 }
mse(1:10, 10:1)
```
# why it does not give a right answer?
```{r}
mse(Boston$medv, predict(lm_ses))

```
```{r}
Splits <-c(rep("train", 253), rep("validation", 152), rep("test", 101))

```
```{r}
boston_master <- Boston %>% mutate(Splits = sample(Splits))
```
```{r}
boston_train <- boston_master %>% filter(Splits == "train")
boston_valid <- boston_master %>% filter(Splits == "validation")
boston_test  <- boston_master %>% filter(Splits == "test")
```
```{r}
model_1 <- lm(medv ~ lstat, data = boston_train)
summary(model_1)

```
```{r}
model_1_mse_train <- mse(y_true = boston_train$medv, y_pred = predict(model_1))
```

```{r}
model_1_mse_valid <- mse(y_true = boston_valid$medv,  y_pred = predict(model_1, newdata = boston_valid))

```
```{r}
model_2 <- lm(medv ~ lstat + age + tax, data = boston_train)
model_2_mse_train <- mse(y_true = boston_train$medv, y_pred = predict(model_2))
model_2_mse_valid <- mse(y_true = boston_valid$medv, 
                         y_pred = predict(model_2, newdata = boston_valid))

```
```{r}
summary(model_2)
```
```{r}
model_1_mse_test <- mse(y_true = boston_valid$medv, 
                         y_pred = predict(model_1, newdata = boston_valid))

```
```{r}
sqrt(model_1_mse_test)
```

```{r}
model_2_mse_test <- mse(y_true = boston_test$medv, 
                        y_pred = predict(model_2, newdata = boston_test))
sqrt(model_2_mse_test)
```
```{r}
mse <- function(y_true, y_pred) mean((y_true - y_pred)^2)
cv_lm <- function(formula, dataset, k) {
 n_samples  <- nrow(dataset)
  select_vec <- rep(1:k, length.out = n_samples)
  data_split <- dataset %>% mutate(folds = sample(select_vec))
   mses <- rep(0, k)
   for (i in 1:k) {
     data_train <- data_split %>% filter(folds != i)
    data_valid <- data_split %>% filter(folds == i) 
   model_i <- lm(formula = formula, data = data_train)
    y_column_name <- as.character(formula)[2]
     
  mses[i] <- mse(y_true = data_valid[[y_column_name]],
                   y_pred = predict(model_i, newdata = data_valid))
   }
   mean(mses)
}
```
```{r}
cv_lm(formula = medv ~ lstat + age + tax, dataset = Boston, k = 9)
cv_lm(formula = medv ~ lstat + I(lstat^2) + age + tax, dataset = Boston, k = 9)
```


```


     
     
  
  


```