---

title: "Practical 3"
author: "Simranjit"
date: "2022-09-29"
output: html_document
---


```{r}
library(tidyverse)
library(magrittr)
library(mice)
library(DAAG)
head(boys)
```
```{r}
tail(boys)

```
```{r}
summary(boys)
```
```{r}

summary(boys)
```
```{r}
boys %>% ggplot(aes(x = age)) + geom_histogram(fill = "dark green") + theme_minimal() +labs(title = "Distribution of age")
```
```{r}
boys %>% ggplot(aes(x = gen)) + geom_bar(fill = "dark green") + theme_minimal() +
  labs(title = "Distribution of genital Tanner stage")

```
```{r}
md.pattern(boys)
```
```{r}
boys_mis <- boys %>%  mutate(gen_mis = is.na(gen), phb_mis = is.na(phb), tv_mis  = is.na(tv))




```
```{r}
boys_mis %>% group_by(gen_mis) %>%  summarize(age = mean(age))
```
```{r} 
boys_mis %>% group_by(phb_mis) %>%
summarize(age = mean(age))
```
```{r}
boys_mis %>% group_by(tv_mis) %>%         summarize(age = mean(age))

```
```{r}
boys_mis %>%
  ggplot(aes(x = age)) +
  geom_histogram(fill = " dark blue") + 
  facet_wrap(~gen_mis) +
  theme_minimal()
```
```{r}
boys_mis %>%
  ggplot(aes(x = age, y = bmi)) +                 geom_point() + theme_minimal() + labs(title = "Scatter plot of age vs bmi")
```

```{r}
boys_mis %>%
  ggplot(aes(x = age, y = bmi, col = gen_mis)) +                 geom_point() + theme_minimal() + labs(title = "Scatter plot of age vs bmi")
```
```{r}
boys_mis %>%
  ggplot(aes(x = age, y = reg)) +                 geom_boxplot(fill = "blue") + theme_minimal() + labs(title = "Scatter plot of age by region")
```
```{r}
boys_mis %>%
  ggplot(aes(x = reg, y = age)) +                 geom_boxplot(fill = "blue") + theme_minimal() + labs(title = "Scatter plot of age by region")
```
```{r}
boys_mis %>%
  ggplot(aes(x = age, fill = gen)) +                 geom_density() + theme_minimal() + 
  scale_fill_brewer() + labs(title = "Density of age by genitial Tanner stage")
```
```{r} 
boys %>%
  mutate(Age = cut(age, 0:22, labels = paste0(0:21, " years")),
         Height = hgt - mean(hgt, na.rm = TRUE)) %>%
  group_by(Age) %>%
  summarize(Height = mean(Height, na.rm = TRUE)) %>%
  mutate(color = ifelse(Height > 0, "Above average", "Below average")) %>%
  ggplot(aes(x = Height, y = Age, fill = color)) +
  geom_bar(stat = "identity") +
  scale_fill_brewer(palette = "Set1") +
  theme_minimal() +
  theme(legend.title = element_blank())
```
```{r}
elastic <- bind_rows("Elastic1" = elastic1,
                     "Elastic2" = elastic2,
                     .id = "Set")
```
```{r}
   elastic %>%
  ggplot(aes(x = stretch, y = distance, col = Set)) +
  geom_point() +
  scale_color_brewer(palette = "Set1") +
  theme_minimal() +
  labs(title = "Elastic bands data")
```
```{r}
elastic %>%
  ggplot(aes(x = stretch, y = distance, col = Set)) + geom_point() +
  geom_smooth(method = "lm") +
  scale_color_brewer(palette = "Set1") +
  theme_minimal() +
  labs(title = "Elastic bands data") 
```
```{r}
 fit1 <- lm(distance ~ stretch, elastic1)
fit2 <- lm(distance ~ stretch, elastic2)
```

```{r}
fit1 %>% predict(se.fit = TRUE)
```
```{r}
fit2 %>% predict(se.fit = TRUE)
```
```{r}
fit1 %>% summary()
```
```{r}
fit2 %>% summary()
```
```{r}

fit1 %>% plot(which = 5)
```
```{r}
fit2 %>% plot(which = 5)
```
```{r}
fit1$residuals
```
```{r}
pred <- predict(fit1, newdata = elastic2)
```
```{r}
pred_dat <- 
  data.frame(distance = pred,  stretch  = elastic2$stretch) %>%
  bind_rows(Predicted = ., Observed  = elastic2, .id = "Predicted")
```
```{r}
pred_dat %>%
  ggplot(aes(stretch, distance, col = Predicted)) + geom_point() + geom_smooth(method = "lm") +  scale_color_brewer(palette = "Set1") + theme_minimal() + labs(title = "Predicted and observed distances")
  
```
 

  