---
title: "Untitled"
author: "Simranjit"
date: "2022-09-26"
output:
  pdf_document: default
  html_document: default
---

```
```{r}
library(ISLR)
library(tidyverse)
library(knitr)
head(Hitters)
hist (Hitters$Salary, xlab = "Salary in thousand of dollars")
  barplot(table(Hitters$League))
  plot(x = Hitters$Hits, y=Hitters$HmRun,
       xlab = "Hits", ylab ="Home runs")
  homeruns_plot <- ggplot(Hitters, aes(x= Hits, y = HmRun)) + geom_point() + labs(x = "Hits", y = "Home runs")
  homeruns_plot
  homeruns_plot + geom_density_2d() + labs(title = "Cool density and scatter plot of baseball data") +theme_minimal()
 
  set.seed(1234)
  student_grade  <- rnorm(32, 7)
  student_number <- round(runif(32) * 2e6 + 5e6)
  programme      <- sample(c("Science", "Social Science"), 32, replace = TRUE)
  gg_students <- tibble ( number = as.character(student_number), 
    grade  = student_grade,                
    prog   = as.factor(programme)         
 )
  head(gg_students)
  ggplot(Hitters, aes(x = HmRun, y = Hits, colour =  League, size = Salary)) + geom_point()+ labs(y = "Hits", x = "Home runs")
  ggplot(Hitters, aes(x = HmRun, y = Hits, colour = League, size = Salary), shape = (League)) + geom_point() + labs(y = "Hits", x = "Home runs")
    gg_students %>%
  ggplot(aes(x = grade)) + geom_histogram(binwidth = .5)
  gg_students %>% 
  ggplot(aes(x = grade)) + geom_density(fill = "light seagreen")
  gg_students %>% 
    ggplot(aes(x = grade)) + geom_density(fill = "Grey") + geom_rug(size = 1, colour = "Red")
    gg_students %>%
    ggplot(aes(x = grade)) + geom_density(fill = "Pink", colour = NA) + geom_rug(size = 1, colour = "Black") + theme_minimal() + labs(y ="" ) + xlim(0, 10)
  gg_students %>% 
    ggplot(aes(x = prog, y = grade, fill = prog)) + geom_boxplot() 
  
  gg_students %>% 
    ggplot(aes(x = prog, y = grade, fill = prog)) + geom_boxplot() + theme_minimal()
  gg_students %>% 
    ggplot(aes(x = grade, fill = prog)) + geom_density(alpha = .5, colour = NA) + geom_rug(size = 1, colour = "light seagreen") +theme_minimal() +
    labs(y = "", fill = "Programme") + xlim(2, 10)
  Hitters %>%
    ggplot(aes(x = Years)) + geom_bar() + theme_minimal()
  Smarket[1:200,] %>%
    mutate(Day = 1:200) %>%
    ggplot(aes(x = Day, y = Volume)) + geom_line() 
  Smarket[1:200,] %>%
    mutate(Day = 1:200) %>%
    ggplot(aes(x = Day, y = Volume)) + geom_line(colour = "Dark Blue",size = 0.8 ) +
    geom_point(colour = "Red", size =2.5) + theme_minimal()
  which.max(Smarket[1:200, ]$Volume)
  max(Smarket[1:200, ]$Today)
  max(Smarket[1:200, ]$Volume)
  Smarket[1:200, ] %>%
    mutate(Day = 1:200) %>%
    ggplot(aes(x = Day, y = Volume)) + geom_line(colour = "Blue", size = 1) +
    geom_label(aes(x = 175, y = 2.5, label = "Peak volume")) + theme_minimal()
  baseball <- Hitters %>%  filter(!is.na(Salary)) %>%  mutate( Salary_range = cut(Salary, breaks = 3,  labels = c("Low salary", "Mid salary", "High salary")), Career_hmrun_proportion = CHmRun/CHits )
  baseball_plot <-   baseball %>% 
    ggplot(aes(x = CWalks, y = Career_hmrun_proportion)) + geom_point() + ylim(0, 0.4) + xlim(0, 1600) + theme_minimal() + labs(y = "Proportion of home runs",
         x = "Career number of walks")  
  baseball_plot
  baseball_plot + facet_wrap(~Salary_range)
  
  
  














```


