---
title: "P3_AleksandraDacko"
author: "Aleksandra Dacko"
date: "9/28/2022"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(magrittr)
library(mice)
library(DAAG)
library(ggplot2)
```

---


# The boys data
```{r}
as.data.frame(head(boys))
```

```{r}
as.data.frame(tail(boys))
```

```{r}
!is.unsorted(boys$age)
```
```{r}
as.datasummary(boys)

```
## 1
```{r}
boys %>% ggplot(aes(x=age))+geom_histogram(fill="pink")+theme_minimal()+ggtitle("Distribution of age")  
```
## 2
```{r}
boys %>%ggplot(aes(x=gen,fill=gen))+geom_bar()+theme_minimal()+ggtitle("Distribution of gen")
```
---
# Assessing missing data
```{r}
md.pattern(boys)
```
## 3

```{r}
boys_missing <- boys %>%
  mutate(gen_mis = factor(is.na(gen), levels = c("FALSE","TRUE"),labels = c("Not Missing", "Missing")),
         phb_mis = factor(is.na(phb), levels = c("FALSE","TRUE"),labels = c("Not Missing", "Missing")),
         tv_mis  = factor(is.na(tv), levels = c("FALSE","TRUE"),labels = c("Not Missing", "Missing")))
```


## 4
```{r missing gen by age}
boys_missing %>% group_by(gen_mis) %>% summarise(age=mean(age))
```


```{r missing tv by age}
boys_missing %>% group_by(tv_mis) %>% summarise(age=mean(age))
```

```{r missing phb by age}
boys_missing %>% group_by(phb_mis) %>% summarise(age=mean(age))
```
## 5

```{r}
gen_mis_lab<-c("Not missing","Missing")
boys_missing %>% ggplot(aes(x=age))+geom_histogram(fill="blue")+facet_wrap(~gen_mis)+theme_minimal()
```
## 6
```{r}
boys %>% ggplot(aes(x=age,y=bmi))+geom_point()+theme_minimal()+ggtitle("Age against bmi")
```

## 7
```{r}
boys_missing %>% ggplot(aes(x=age,y=bmi,colour=gen_mis))+geom_point()+theme_minimal()+ggtitle("Age against bmi")+geom_smooth(method = "loess")
```
# Visualizing the boys data

## 8
```{r}
boys %>% ggplot(aes(x=reg,y=age, fill=reg))+geom_boxplot()+ggtitle("Distribution of age over regions")+theme(legend.position="none",axis.title.x =element_blank(),plot.title=element_text(size=14,hjust = 0.5))
```
## 9
```{r}
boys %>% ggplot(aes(x=age, fill=gen))+geom_density(alpha=0.6)+ggtitle("Distribution of age over regions")+theme_minimal()+scale_fill_brewer(palette =2 )
```

## 10
```{r}
boys %>%
  mutate(Age = cut(age, 0:22, labels = paste0(0:21, " years")),
         Height = hgt - mean(hgt, na.rm = TRUE)) %>%
  group_by(Age) %>%
  summarize(Height = mean(Height, na.rm = TRUE)) %>%
  mutate(color = ifelse(Height > 0, "Above average", "Below average")) %>%
  ggplot(aes(x = Height, y = Age, fill = color)) +
  geom_bar(stat = "identity") +
  scale_fill_brewer(palette = "Set2") +
  theme_minimal() +
  theme(legend.title = element_blank())

```
---
# Regression visualization
## 11
```{r}
elastic <- bind_rows("Elastic1" = elastic1,
                     "Elastic2" = elastic2,
                     .id = "Set")
rownames(elastic) <- NULL  
head(elastic)
```

## 12
```{r}
elastic %>% ggplot(aes(x=stretch,y=distance,colour=Set))+geom_point()+theme_minimal()+ggtitle("Elastic bands")
```
## 13
```{r}
elastic %>% ggplot(aes(x=stretch,y=distance,colour=Set))+geom_point()+theme_minimal()+geom_smooth(method = "lm")+ggtitle("Elastic bands")
```

## 14
```{r}
lm_elastic1<-elastic1 %>% lm(distance~ stretch,data=.) 
lm_elastic2 <-elastic2 %>% lm(distance~ stretch,data=.) 

```

## 15
```{r}
lm_elastic1 %>% predict(se.fit=T)

```

```{r}
lm_elastic2 %>% predict(se.fit=T)

```

```{r}
lm_elastic1 %>% summary()
```

```{r}
lm_elastic2 %>% summary()
```

```{r}
lm_elastic1 %>% summary()%$% paste("For elastic 1 model the R^2 is: ",round(r.squared,3))
```

```{r}
lm_elastic2 %>% summary()%$% paste("For elastic 2 model the R^2 is: ",round(r.squared,3))
```


## 16 
```{r}
lm_elastic1 %>% plot(which = 5)
lm_elastic2 %>% plot(which = 5)

```
## 17
```{r}
pred <- predict(lm_elastic1, newdata = elastic2)
```

## 18
```{r}
pred_dat <- 
  data.frame(distance = pred, 
             stretch  = elastic2$stretch) %>%
  bind_rows(Predicted = .,
            Observed  = elastic2, 
            .id = "Predicted")

pred_dat %>%
  ggplot(aes(stretch, distance, col = Predicted)) +
  geom_point() + 
  geom_smooth(method = "lm") +
  scale_color_brewer(palette = "Set1") +
  theme_minimal() +
  labs(title = "Predicted and observed distances")
```

```{r}
cor(elastic2$distance, pred)

```






