---
editor_options:
  markdown:
    wrap: 72
---

library(ISLR) library(tidyverse) library(haven) library(readxl)

##Question 1:

object_1 \<- 1:5 object_2 \<- 1L:5L object_3 \<- "-123.456" object_4 \<-
as.numeric(object_2) object_5 \<- letters[object_1] object_6 \<-
as.factor(rep(object_5, 2)) object_7 \<- c(1, 2, 3, "4", "5", "6")

class(object_1) class(object_2) class(object_3) class(object_4)
class(object_5) class(object_6) class(object_7)

##Question 2:

object_7 \<- as.numeric(object_7) class(object_7)

##Question 3:

objects \<- list(object_1, object_2, object_3, object_4, object_5,
object_6, object_7)

##Question 4:

objects_frame \<- data.frame(object_1, object_2, object_5)

##Question 5:

ncol(objects_frame) nrow(objects_frame)

##Question 6:

apps \<- read_csv("googleplaystore.csv")

##Question 7:

#Size, installs, price, content rating; all of these are stored as
character \#(chr) variable types, while one would expect them to be
numeric.

##Question 8:

head(apps)

##Question 9:

students \<- read_excel("students.xlsx") head(students) ncol(students)
nrow(students)

#I wouldn't expect student_number to be a dbl variable, instead of a
numeric one

##Question 10:

summary(students)

#The range of grades is between 4.844 and 9.291

##Question 11:

low_grades \<- filter(students, grade \< 5.5)

##Question 12:

high_grades_A \<- filter(students, grade \> 8, programme == "A")

##Question 13:

arrange(students, programme, -grade)

##Question 14:

select(students, student_number, programme)

##Question 15:

students_recoded \<- mutate(students, programme = recode(programme, "A"
= "Science", "B" = "Social_Science")) head(students_recoded)

##Question 16:

popular_apps \<- read_csv("googleplaystore.csv") %\>% mutate(Downloads =
parse_number(Installs)) %\>% filter(Downloads \> 500000000) %\>%
arrange(-Rating) %\>% select(App, Category, Rating, Downloads)

head(popular_apps)

##Question 17:

mad \<- function(x) { median(abs(x - median(x))) }

popular_apps %\>% summarise( median_D = median(Downloads), min_D =
min(Downloads), max_D = max(Downloads), mad = mad(Downloads) )

##Question 18:

#See the code in question 17

##Question 19: popular_apps %\>% group_by(Category) %\>% summarise(
median_D = median(Downloads), min_D = min(Downloads), max_D =
max(Downloads), mad = mad(Downloads) )

##Question 20:

#What category of app has the highest mean rating?

popular_apps %\>% group_by(Category) %\>% summarise( mean = mean(Rating)
) %\>% arrange(-mean)

#Seems like we've got a shared highest rating, with both GAME and
#Photography scoring a 4.5!
