---
title: "Assignment 1"
author: "Aleksandra Dacko"
date: "9/28/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(magrittr)
library(here)
library(gridExtra)

options(dplyr.summarise.inform = FALSE)
```

```{r}
data<-read.csv(file="Data/ICAO_accidents.csv",header = T)
```

```{r}

head(data)
```

### In this part I would like to decode the missing name of the factors to Unknown or somthing more informative
```{r}
#to limit ourselves 
#remove to specific information and duplicates
data %<>% mutate("AircraftType"=case_when(Airplane=="True"~"Airplane",
                                     Helicopter=="True"~"Helicopter"),
                "WeightCat"=case_when(Over5700=="True"~">5700",
                                        Over2250=="False" ~ "<2250",
                                        Over2250=="True" & Over5700=="False" ~"2250-5700"))%>% 
  select(!c("Location","Operator","Date","Model","StateOfOperator","Class","ScheduledCommercial","Official","OccCats","Over2250","Over5700","Helicopter","Airplane","Registration","X")) %>% mutate_if(is.character, as.factor) 

levels(data$Risk)[1]<-"Unknown"
levels(data$StateOfOccurrence)[1]<-"Unknown"
levels(data$StateOfRegistry)[1]<-"Unknown"
levels(data$FlightPhase)[1]<-"Unknown"
levels(data$InjuryLevel)[1]<-"Unknown"

str(data)


```

```{r}
#frequencies
data %$% table(AircraftType)

frq.per.country<-data %>% group_by(StateOfOccurrence) %>% 
  summarise(count=n()) %>% 
  arrange(.,desc(count))

frq.per.FlightPhase<-data %>% group_by(FlightPhase) %>% 
  summarise(count=n()) %>% 
  arrange(.,desc(count))

data %>% group_by(InjuryLevel) %>% 
  summarise(count=n()) %>% 
  arrange(.,desc(count))

data %>% group_by(Risk) %>% 
  summarise(count=n()) %>% 
  arrange(.,desc(count))



frq.flightPhase.by.InjuryLevel<-data %>% group_by(FlightPhase, InjuryLevel) %>% 
  summarise(count=n())

```

```{r}
#plots

# frequency of accidents by flight phase (Landing, Take-off, etc.) grouped by aircraft type (Airplane, Helicopter)
FlightPhase.order.ap<-data %>%subset(AircraftType=="Airplane") %>% group_by(FlightPhase) %>% 
  summarise(count=n()) %>% 
  arrange(.,count) %$% FlightPhase
FlightPhase.order.hel<-data %>%subset(AircraftType=="Helicopter") %>% group_by(FlightPhase) %>% 
  summarise(count=n()) %>% 
  arrange(.,count) %$% FlightPhase

data %>%subset(AircraftType=="Airplane") %>% ggplot( aes(x=factor(FlightPhase, FlightPhase.order.ap))) +
  geom_bar(aes(y = (..count..)/sum(..count..)))+
  coord_flip() +
  scale_y_continuous(labels=scales::percent,limits=c(0,0.40))+
  geom_text(aes( label = scales::percent((..count..)/sum(..count..)),
                   y= (..count..)/sum(..count..) ), stat= "count",hjust=-0.25) +
  labs(x = "Flight Phase", y="Percentage", title = "Airplane")+theme_minimal()
data %>%subset(AircraftType=="Helicopter") %>% ggplot( aes(x=factor(FlightPhase, FlightPhase.order.hel))) + 
  geom_bar(aes(y = (..count..)/sum(..count..)))+
  coord_flip() +
  scale_y_continuous(labels=scales::percent,limits=c(0,0.40))+
  geom_text(aes( label = scales::percent((..count..)/sum(..count..)),
                   y= (..count..)/sum(..count..) ), stat= "count", hjust =-0.25 ) +
  labs(x = "Flight Phase", y="Percentage",title = "Helicopter")+theme_minimal()

#checks of hte numbers -- correct 
subset(data, AircraftType=="Airplane" & FlightPhase=="Take-off") %>% nrow / subset(data, AircraftType=="Airplane") %>% nrow
subset(data, AircraftType=="Helicopter" & FlightPhase=="Take-off") %>% nrow / subset(data, AircraftType=="Helicopter") %>% nrow

```

```{r}
# frequency of accidents in each flight pahse grouped by InjuryLevel
ggplot(data = data[data$InjuryLevel %in% c("Fatal", "Minor", "Serious", "None", "Unknown"),], aes(x=FlightPhase, group=InjuryLevel)) + 
  geom_bar(aes(y = (..count..)/sum(..count..)))+
  coord_flip() +
  scale_y_continuous(labels=scales::percent,limits=c(0,0.16))+
  geom_text(aes( label = scales::percent((..count..)/sum(..count..)),
                   y= (..count..)/sum(..count..) ), stat= "count", hjust =-0.25 )+
  facet_wrap(~ InjuryLevel)+
  labs(x = "Flight Phase", y="Percentage")



```
```{r}
#order of the legend could be changed here is my proposition of a graph. The bad thing is that they are faced wraped but the frequencies are for whole dataset 
data %>% ggplot( aes(x=FlightPhase, fill=InjuryLevel)) + 
  geom_bar(aes(y = (..count..)/sum(..count..)),position = "dodge") +scale_y_continuous(labels=scales::percent)+facet_wrap(~AircraftType,scales = "free_y")+theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),panel.grid.major = element_line(colour = "grey"),panel.grid.minor = element_line(colour = "grey"),panel.grid.major.x = element_blank(),
  panel.grid.minor.x = element_blank()
, panel.background = element_blank())
```


```{r}
ggplot(data = data, aes(x=FlightPhase, group=WeightCat)) + 
  geom_bar(mapping = aes(y=..prop..), stat="count") +
  coord_flip() +
  facet_wrap(~ WeightCat)+
  geom_text(aes(label = scales::percent(..prop..), y= ..prop..), stat= "count", size=3, hjust = -0.2 )  +
  scale_y_continuous(labels = scales::percent)+
  labs(x = "Flight Phase", y="Percentage")
```


```{r}
#number of accidents per year - trend
data_ac_ct<- data %>% group_by(Year,AircraftType) %>% 
  summarise(count=n())
data_ac_ct
```


```{r}
data_ac_ct %>% ggplot(aes(x=Year, y=count,color=AircraftType)) + 
  geom_line() +
  labs(x = "Year", y="Count")+theme_minimal()+ ggtitle("The accident count")

#there was a major drop in the number of accidents from 2012 onwards, so maybe split the data to before and after 2012 and investigate what else changed
```
## Investigatio of the drop
```{r}

```

## My research questions 
### How many people died “depending on some factors” or over time? (I would not include helicopters, since they only can carry a few people in them)

```{r}
#distribution of number of engines
table<-data %>%subset(AircraftType=="Airplane" & InjuryLevel=="Fatal") %$% table(Engines) %>% transform() %>% rename("Count" ="Freq" )
table
#since only one with 6 engines I checked how many people died (15) we can directly report where it happened and we wont include it in the next graph
data %>%subset(AircraftType=="Airplane" & InjuryLevel=="Fatal") %>% group_by(Engines) %>% summarise(sum(Fatalities,na.rm = T))

```

```{r}
#since there was only one plane with 6 engenes I droped it and 
data %>%subset(AircraftType=="Airplane" & InjuryLevel=="Fatal"& Engines<6) %>% ggplot(aes(x=as.factor(Engines),y=Fatalities))+geom_boxplot()+geom_jitter()+theme_minimal() 

```

