---
title: "Timo_van_Veghel_Practical_5"
author: "Timo"
date: "2022-11-05"
output: html_document
---
```{r}
library(MASS)
library(class)
library(ISLR)
library(tidyverse)
```
```{r}
set.seed(45)
```

##Question 1:

```{r}
Default %>% 
  arrange(default) %>% 
  ggplot(aes(x = balance, y = income, colour = default)) +
  geom_point(size = 1.3) +
  theme_minimal() +
  scale_colour_viridis_d()
```
##Question 2:

```{r}
Default %>% 
  arrange(default) %>% 
  ggplot(aes(x = balance, y = income, colour = default)) +
  geom_point(size = 1.3) +
  theme_minimal() +
  scale_colour_viridis_d() +
  facet_grid(cols = vars(student))
```
What we see is that the most of the low income datapoints are students.

##Question 3:

```{r}
default_df <-
  Default %>% 
  mutate(student = ifelse(student == "Yes", 1, 0)) %>% 
  mutate(split = sample(rep(c("train", "test"), times = c(8000, 2000))))

default_train <-
  default_df %>% 
  filter(split == "train") %>% 
  select(-split)

default_test <-
  default_df %>% 
  filter(split == "test") %>% 
  select(-split)

```

##Question 4:

```{r}
knn_5_pred <- knn(
  train = default_train %>% select(-default),
  test = default_test %>% select(-default),
  cl = as_factor(default_train$default),
  k = 5
)
```

##Question 5:

```{r}
default_test %>% 
  arrange(default) %>% 
  ggplot(aes(x = balance, y = income, colour = default)) +
  geom_point(size = 1.3) +
  scale_colour_viridis_d() +
  theme_minimal() +
  labs(title = "True class")
```

```{r}
bind_cols(default_test, pred = knn_5_pred) %>% 
  arrange(default) %>% 
  ggplot(aes(x = balance, y = income, colour = pred)) +
  geom_point(size = 1.3) +
  scale_colour_viridis_d() +
  theme_minimal() +
  labs(title = "Predicted class (5nn)")
```

##Question 6:

```{r}
knn_2_pred <- knn(
  train = default_train %>% select(-default),
  test = default_test %>% select(-default),
  cl = as_factor(default_train$default),
  k = 2
)

bind_cols(default_test, pred = knn_2_pred) %>% 
  arrange(default) %>% 
  ggplot(aes(x = balance, y = income, colour = pred)) +
  geom_point(size = 1.3) +
  scale_colour_viridis_d() +
  theme_minimal() +
  labs(title = "Predicted class (2nn)")
```

##Question 7:

```{r}
table(true = default_test$default, predicted = default_test$default)
```

##Question 8:

```{r}
table(true = default_test$default, predicted = knn_5_pred)
table(true = default_test$default, predicted = knn_2_pred)
```

##Question 9:

```{r}
lr_mod <- glm(default ~ ., family = binomial, data = default_train)
```

##Question 10:

```{r}
tibble(observed = default_train$default, 
       predicted = predict(lr_mod, type = "response")) %>% 
  ggplot(aes(y = predicted, x = observed, colour = observed)) +
  geom_point(position = position_jitter(width = 0.2), alpha = 0.3) +
  scale_colour_manual(values = c("dark blue", "orange"), guide = "none") +
  theme_minimal() +
  labs(y = "Predicted probability to default")
```

##Question 11:

```{r}
coefs <- coef(lr_mod)
coefs["balance"]

logodds <- coefs[1] + 4e4*coefs[4] + 3e3*coefs[3]

1/(1 + exp(-logodds))
```

##Question 12:

```{r}
balance_df <- tibble(
  student = rep(0, 500),
  balance = seq(0, 3000, length.out = 500),
  income = rep(mean(default_train$income), 500)
)
```

##Question 13:

```{r}
balance_df$predprob <- predict(lr_mod, newdata = balance_df, type = "response")

balance_df %>% 
  ggplot(aes(x = balance, y = predprob)) +
  geom_line(col = "dark blue", size = 1) +
  theme_minimal()
```
##Question 14:

```{r}
pred_prob <- predict(lr_mod, newdata = default_test, type = "response")
pred_lr <- factor(pred_prob > .5, labels = c("Yes", "No"))

table(true = default_test$default, predicted = pred_lr)
```

##Question 15:

```{r}
lda_mod <- lda(default ~ ., data = default_train)
```

##Question 16:

```{r}
lda_mod
```

##Question 17:

```{r}
pred_lda <- predict(lda_mod, newdata = default_test)
table(true = default_test$default, predicted = pred_lda$class)

```

##Question 18:

```{r}
titanic <- read_csv("Titanic.csv")

lr_mod_titanic <- glm(Survived ~ PClass * Sex * Age, data = titanic)

predict(lr_mod_titanic,
        newdata = tibble (
          PClass = c("3rd", "2nd"),
          Age = c(14, 14),
          Sex = c("male", "female")
        ),
        type = "response"
      )
```

