---
title: "Classification"
author: "Simranjit"
date: "2022-10-10"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(MASS)
library(class)
library(ISLR)
library(tidyverse)

```
```{r}
set.seed(30)
```
#Default dataset
```{r}
Default %>%
  ggplot(aes(x = balance, y = income, colour = default)) + geom_point(size = 0.2) + theme_minimal() + geom_smooth() + scale_alpha_binned() + scale_colour_viridis_d()

```
```{r}
Default %>%
arrange(default) %>%
ggplot(aes(x = balance, y = income, colour = default)) +
  geom_point(size = 0.3) +
  theme_minimal() +
  scale_colour_viridis_d() +
  facet_grid(cols = vars(student))
```
```{r}
default_df <- 
  Default %>%
  mutate(student = ifelse(student == "Yes", 1,0)) %>%
  mutate(split = sample(rep(c("train","test"), times = c(8000, 2000))))
default_train <- 
  default_df %>%
  filter(split == "train") %>%
  select(-split)
default_test <-
  default_df%>%
  filter(split == "test") %>%
  select(-split)


```
#K-Nearest Neighbours
```{r}
knn_5_pred <- knn(train = default_train %>% select(-default),
 test = default_test %>% select(-default),
 cl = as_factor(default_train$default),
 k = 5)
```
```{r}
default_test %>% 
  arrange(default) %>% 
  ggplot(aes(x = balance, y = income, colour = default)) +
  geom_point(size = 1) + 
  scale_colour_viridis_d() +
  theme_minimal() +
  labs(title = "True class")

```
```{r}
bind_cols(default_test, pred = knn_5_pred) %>% 
  arrange(default) %>% 
  ggplot(aes(x = balance, y = income, colour = pred)) +
  geom_point(size = 1) + 
  scale_colour_viridis_d() +
  theme_minimal() +
  labs(title = "Predicted class")


```
```{r}
knn_2_pred <- knn(
  train = default_train %>% select(-default),
  test  = default_test  %>% select(-default),
  cl    = as_factor(default_train$default),
  k     = 2
)

# second plot maps pred to colour
bind_cols(default_test, pred = knn_2_pred) %>% 
  arrange(default) %>% 
  ggplot(aes(x = balance, y = income, colour = pred)) +
  geom_point(size = 1) + 
  scale_colour_viridis_d() +
  theme_minimal() +
  labs(title = "Predicted class (2nn)")
```
#Confusion Matrix
```{r}
table(true = default_test$default, predicted = knn_2_pred)
```
```{r}
table(true = default_test$default, predicted = default_test$default)
```
```{r}
table(true = default_test$default, predicted = knn_5_pred)
```
#Logistic regression
```{r}
lr_mod <- glm(default ~ ., family = binomial, data = default_train)
```

```{r}
tibble(observed  = default_train$default, 
       predicted = predict(lr_mod, type = "response")) %>% 
  ggplot(aes(y = predicted, x = observed, colour = observed)) +
  geom_point(position = position_jitter(width = 0.2), alpha = .3) +
  scale_colour_manual(values = c("dark blue", "orange"), guide = "none") +
  theme_minimal() +
  labs(y = "Predicted probability to default")

```
```{r}
coefs <- coef(lr_mod)
coefs["balance"]
```
```{r}
logodds <- coefs[1] + 4e4*coefs[4] + 3e3*coefs[3]
1 / (1 + exp(-logodds))
```
#Visualising the effect of the balance variable

````{r}
balance_df <- tibble(
  student = rep(0, 500),
  balance = seq(0, 3000, length.out = 500),
  income  = rep(mean(default_train$income), 500)
)
```

```{r}
balance_df$predprob <- predict(lr_mod, newdata = balance_df, type = "response")

balance_df %>% 
  ggplot(aes(x = balance, y = predprob)) +
  geom_line(col = "dark blue", size = 1) +
  theme_minimal()
```
```{r}

pred_prob <- predict(lr_mod, newdata = default_test, type = "response")
pred_lr   <- factor(pred_prob > .5, labels = c("No", "Yes"))

table(true = default_test$default, predicted = pred_lr)
```
#Linear Discriminent analysis
```{r}
lda_mod <- lda(default ~ ., data = default_train)
```
```{r}
lda_mod
```
```{r}
pred_lda <- predict(lda_mod, newdata = default_test)
table(true = default_test$default, predicted = pred_lda$class)
```
##Assignment
```{r}
titanic <- read_csv("Data/Titanic.csv")
```
```{r}
lr_mod_titanic <- glm(Survived ~ PClass * Sex * Age, data = titanic)

predict(lr_mod_titanic, 
        newdata = tibble(
          PClass = c( "3rd",    "2nd"),
          Age    = c(    14,       14), 
          Sex    = c("male", "female")
        ), 
        type = "response"
)
```
